### PR TITLE
a new /home 2019 logo

### PR DESCRIPTION
**Pull request by martinnagellarsen**

### CODE REVIEW

**Comment by valberg** [comment]
Shouldn't the H be the same size as the B? Other than that, so awesome! :smile:

**Comment by flummer** [comment]
Looks good to me! What file has a differently sized H?

**Comment by valberg** [comment]
Ah it's https://github.com/bornhack/assets/blob/437b3bd7315f9ce80359a20b388ff53b482d992b/2019/logo/A_New_Home/bornhack_logo_yellow_black.pdf that has a "small" H. 

https://github.com/bornhack/assets/blob/437b3bd7315f9ce80359a20b388ff53b482d992b/2019/logo/A_New_Home/bornhack_logo_pos_traditional.pdf for instance is fine.

**Comment by martinnagellarsen** [comment]
> 
> 
> Ah it's https://github.com/bornhack/assets/blob/437b3bd7315f9ce80359a20b388ff53b482d992b/2019/logo/A_New_Home/bornhack_logo_yellow_black.pdf that has a "small" H.
> 
> https://github.com/bornhack/assets/blob/437b3bd7315f9ce80359a20b388ff53b482d992b/2019/logo/A_New_Home/bornhack_logo_pos_traditional.pdf for instance is fine.

Right, the yellow on black was a file from the design process that got left in there. Disregard that one. :-)

**Comment by valberg** [comment]
@martinnagellarsen roger :) great work!

**Comment by flummer** [comment]
I suggest we remove the two that is not correct and merge in the rest, just so that nobody uses the incorrect ones by mistake.

**Comment by martinnagellarsen** [comment]
Done! :-)

**Pull request merged**
